#!/bin/sh
LOOP=${LOOP:-0}
LOOP_DEV=${LOOP_DEV:-/dev/loop$LOOP}
NAME=${NAME:-$(uname -n)}
FILE=${FILE:-/var/local/$NAME.secretfs}
SIZE_GB=${SIZE_GB:-25}
MOUNT=${MOUNT:-/mnt/$NAME}
SECRETFS=${SECRETFS:-secretfs$LOOP}
TYPE=${TYPE:-"mapper"}

echo_env() {
    printf " LOOP_DEV=\t%s\n" "$LOOP_DEV"
    printf " FILE=\t%s\n" "$FILE"
    printf " MOUNT=\t%s\n" "$MOUNT"
    printf " SECRETFS=\t%s\n" "$SECRETFS"
    printf " TYPE=\t%s\n" "$TYPE"
    printf " SIZE_GB=\t%s\n" "$SIZE_GB"
}

check_command() {
    COMMAND=$1
    if ! command -v "$COMMAND" > /dev/null 2>&1
    then
        echo "Command $COMMAND could not be found, make sure it is installed"
        exit
    fi
}

check_commands() {
    check_command dd
    check_command chmod
    check_command losetup    
    check_command cryptsetup    
    check_command mke2fs    
    check_command tune2fs    
}

if [ "x$1" != "xrun" ]; then
    echo "Usage: $0 run|test"
    if [ "$1" = "test" ]; then
        echo_env
        check_commands
    fi
    exit
fi

